/**
 * VerifyPage.js
 * Public drug verification page — no authentication required.
 *
 * Route: /verify/:drugID
 *
 * QR codes generated by the backend encode a URL like:
 *   <BASE_URL>/verify/<drugID>
 *
 * When a consumer scans the QR code they land here.
 * This page calls GET /getDrug/:id (the existing backend endpoint)
 * to fetch drug details and display authenticity status.
 *
 * No JWT is attached — this is intentionally public.
 * Uses a plain axios call (not the authenticated `api` instance)
 * so a 401 interceptor never fires on a public route.
 */

import React, { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import axios from "axios";

const BASE_URL =
  process.env.REACT_APP_API_URL || "http://localhost:3000";

function VerifyPage() {
  const { drugID } = useParams();
  const [drug,    setDrug]    = useState(null);
  const [loading, setLoading] = useState(true);
  const [error,   setError]   = useState("");

  useEffect(() => {
    if (!drugID) return;

    async function fetchDrug() {
      try {
        setLoading(true);
        const res = await axios.get(`${BASE_URL}/getDrug/${drugID}`);
        setDrug(res.data);
      } catch (err) {
        setError(
          err.response?.data?.error ||
          "Drug not found. It may be counterfeit or the ID is invalid."
        );
      } finally {
        setLoading(false);
      }
    }

    fetchDrug();
  }, [drugID]);

  const getStatus = (d) => {
    if (!d) return { label: "", color: "#555" };
    const currentTime = Math.floor(Date.now() / 1000);
    const exp  = Number(d.expiryDate);
    const risk = Number(d.riskScore);
    if (!d.exists)          return { label: "❌ Fake Drug",       color: "#dc3545" };
    if (exp < currentTime)  return { label: "⚠️ Expired Drug",    color: "#fd7e14" };
    if (risk > 70)          return { label: "🚨 High Risk Drug",  color: "#dc3545" };
    return                         { label: "✅ Authentic Drug",  color: "#28a745" };
  };

  const formatDate = (ts) => new Date(Number(ts) * 1000).toDateString();

  const status = drug ? getStatus(drug) : null;

  return (
    <div style={styles.page}>
      <div style={styles.card}>
        {/* Brand */}
        <div style={styles.brand}>
          <span style={styles.brandIcon}>💊</span>
          <span style={styles.brandName}>PharmChain AI</span>
        </div>
        <p style={styles.subtitle}>Drug Verification</p>
        <hr style={styles.divider} />

        {loading && (
          <div style={styles.center}>
            <div style={styles.spinner} />
            <p style={styles.loadingText}>Verifying drug…</p>
          </div>
        )}

        {!loading && error && (
          <div style={styles.errorBox}>
            <p style={styles.errorText}>❌ {error}</p>
          </div>
        )}

        {!loading && drug && (
          <>
            {/* Status badge */}
            <div
              style={{
                ...styles.statusBadge,
                background: status.color,
              }}
            >
              {status.label}
            </div>

            {/* Drug details */}
            <table style={styles.table}>
              <tbody>
                {[
                  ["Drug ID",    drug.drugID],
                  ["Name",       drug.name],
                  ["Batch",      drug.batchNumber],
                  ["Expiry",     formatDate(drug.expiryDate)],
                  ["Owner",      drug.currentOwner],
                  ["Risk Score", drug.riskScore],
                ].map(([label, value]) => (
                  <tr key={label}>
                    <td style={styles.tdLabel}>{label}</td>
                    <td style={styles.tdValue}>{value}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </>
        )}

        <p style={styles.footer}>
          <Link to="/login" style={styles.link}>
            Login to manage drugs →
          </Link>
        </p>
      </div>
    </div>
  );
}

// ─── Inject keyframes (spin + fadeIn) ────────────────────────────────────
if (!document.getElementById("verify-page-keyframes")) {
  const s = document.createElement("style");
  s.id = "verify-page-keyframes";
  s.textContent = `
    @keyframes spin    { to { transform: rotate(360deg); } }
    @keyframes fadeIn  { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }
  `;
  document.head.appendChild(s);
}

const styles = {
  page: {
    minHeight:      "100vh",
    background:     "linear-gradient(135deg, #eef2f7, #dbe6f6)",
    display:        "flex",
    alignItems:     "center",
    justifyContent: "center",
    fontFamily:     "'Segoe UI', Arial, sans-serif",
    padding:        "20px",
  },
  card: {
    background:   "#fff",
    borderRadius: "16px",
    boxShadow:    "0 8px 32px rgba(0,0,0,0.12)",
    padding:      "36px 32px",
    width:        "100%",
    maxWidth:     "440px",
    textAlign:    "center",
    animation:    "fadeIn 0.4s ease-in",
  },
  brand: {
    display:        "flex",
    alignItems:     "center",
    justifyContent: "center",
    gap:            "8px",
    marginBottom:   "4px",
  },
  brandIcon: { fontSize: "28px" },
  brandName: { fontWeight: "800", fontSize: "22px", color: "#1a1a2e" },
  subtitle:  { color: "#888", fontSize: "13px", margin: "0 0 0 0" },
  divider:   { border: "none", borderTop: "1px solid #eee", margin: "16px 0" },
  center:    { display: "flex", flexDirection: "column", alignItems: "center", gap: "10px", padding: "20px 0" },
  spinner: {
    width: "36px", height: "36px",
    border: "4px solid #dbe6f6", borderTop: "4px solid #4facfe",
    borderRadius: "50%", animation: "spin 0.8s linear infinite",
  },
  loadingText: { color: "#888", fontSize: "14px" },
  errorBox:  { background: "#fff0f0", border: "1px solid #f5c6cb", borderRadius: "10px", padding: "14px", marginBottom: "16px" },
  errorText: { margin: 0, color: "#721c24", fontSize: "14px" },
  statusBadge: {
    display:      "inline-block",
    color:        "#fff",
    fontWeight:   "700",
    fontSize:     "16px",
    padding:      "10px 24px",
    borderRadius: "30px",
    marginBottom: "20px",
  },
  table:   { width: "100%", borderCollapse: "collapse", marginBottom: "20px", textAlign: "left" },
  tdLabel: { padding: "8px 10px", fontWeight: "600", color: "#555", fontSize: "13px", width: "38%", borderBottom: "1px solid #f0f0f0" },
  tdValue: { padding: "8px 10px", color: "#333", fontSize: "13px", borderBottom: "1px solid #f0f0f0", wordBreak: "break-all" },
  footer:  { marginTop: "8px", fontSize: "13px" },
  link:    { color: "#4facfe", textDecoration: "none", fontWeight: "600" },
};

export default VerifyPage;
